<a href="https://colab.research.google.com/github/samratchakraborty422000/Python-Practice/blob/main/Pandas_Practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('services.csv') # creating a dataframe

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [6]:
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [7]:
df.head(5) # top 5 data

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN

In [8]:
df.tail(5) # bottom 5 data

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [11]:
df.dtypes #datatypes of columns

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [12]:
df['location_id'] # accessing a column

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    22
Name: location_id, dtype: int64

In [13]:
type(df['location_id']) # one dimentional series

pandas.core.series.Series

In [14]:
df[['location_id']]

    location_id
0             1
1             2
2             3
3             4
4             5
5             6
6             7
7             8
8             9
9            10
10           11
11           12
12           13
13           14
14           15
15           16
16           17
17           18
18           19
19           20
20           21
21           22
22           22

In [15]:
type(df[['location_id']]) # two dimentional dataframe

pandas.core.frame.DataFrame

In [16]:
df[['keywords','status']]

                                             keywords    status
0   ADULT PROTECTION AND CARE SERVICES, Meal Sites...    active
1   EMPLOYMENT/TRAINING SERVICES, Job Development,...    active
2   Geriatric Counseling, Older Adults, Gay, Lesbi...    active
3   INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...    active
4      COMMUNITY SERVICES, Speakers, Automobile Loans    active
5   ADULT PROTECTION AND CARE SERVICES, In-Home Su...    active
6   ADULT PROTECTION AND CARE SERVICES, Adult Day ...    active
7   ADULT PROTECTION AND CARE SERVICES, Meal Sites...    active
8   EDUCATION SERVICES, Library, Libraries, Public...    active
9   EDUCATION SERVICES, Library, Libraries, Public...    active
10  EDUCATION SERVICES, Library, Libraries, Public...    active
11  EDUCATION SERVICES, Adult, Alternative, Litera...    active
12  EDUCATION SERVICES, Library, Libraries, Public...    active
13  COMMUNITY SERVICES, Interpretation/Translation...    active
14  ALCOHOLISM SERVICES, Residential Care, DRUG AB...    active
15  COMMODITY SERVICES, Clothing/Personal Items, C...    active
16  COMMODITY SERVICES, Clothing/Personal Items, C...    active
17  HEALTH SERVICES, Outpatient Care, Community Cl...    active
18  HEALTH SERVICES, Outpatient Care, Community Cl...    active
19                                                NaN   defunct
20                                                NaN  inactive
21                                    Salud, Medicina    active
22         Ruby on Rails/Postgres/Redis, testing, wic    active

In [17]:
df1=pd.read_excel("LUSID Excel - Setting up your market data.xlsx") #loading from excel file

In [19]:
df1.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Datetimes in LUSID,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,This sheet allows you to format datetimes for...,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,If you have any questions please visit our:,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df1.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')

In [21]:
df1['Unnamed: 0']

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
20   NaN
21   NaN
22   NaN
23   NaN
24   NaN
25   NaN
26   NaN
27   NaN
Name: Unnamed: 0, dtype: float64

In [25]:
#loading from weblink
df3=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [31]:
df3.to_csv("titanic.csv",index=False)

#it will save the file to csv
'''index=False: This tells Pandas not to write the DataFrame index to the CSV file.
Without this, the index (row labels) would be saved as the first column, which is often not needed unless the index has special meaning.
'''

'index=False: This tells Pandas not to write the DataFrame index to the CSV file.\nWithout this, the index (row labels) would be saved as the first column, which is often not needed unless the index has special meaning.\n'

In [32]:
import lxml #loading data from html or xml
url_data = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2015_totals.html")

In [33]:
type(url_data)

list

In [34]:
df4=url_data[0]

In [35]:
df4.head()

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
0,1.0,James Harden,25.0,HOU,SG,81.0,81.0,2981.0,647.0,1470.0,...,384.0,459.0,565.0,154.0,60.0,321.0,208.0,2217.0,4.0,"MVP-2,AS,NBA1"
1,2.0,Stephen Curry,26.0,GSW,PG,80.0,80.0,2613.0,653.0,1341.0,...,285.0,341.0,619.0,163.0,16.0,249.0,158.0,1900.0,0.0,"MVP-1,AS,NBA1"
2,3.0,Russell Westbrook,26.0,OKC,PG,67.0,67.0,2302.0,627.0,1471.0,...,364.0,488.0,574.0,140.0,14.0,293.0,184.0,1886.0,11.0,"MVP-4,AS,NBA2"
3,4.0,LeBron James,30.0,CLE,SF,69.0,69.0,2493.0,624.0,1279.0,...,365.0,416.0,511.0,109.0,49.0,272.0,135.0,1743.0,2.0,"MVP-3,DPOY-13,AS,NBA1"
4,5.0,Damian Lillard,24.0,POR,PG,82.0,82.0,2925.0,590.0,1360.0,...,329.0,378.0,507.0,97.0,21.0,222.0,164.0,1720.0,0.0,AS

In [36]:
df4.to_csv("players.csv" , index=False)